version: '3'

services:
    nats-server:
        image: nats:latest

    client-gateway:
        build:
            context: ./client-gateway
            dockerfile: dockerfile.prod
        image: client-gateway-prod
        ports:
            - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
        environment:
            - PORT=${CLIENT_GATEWAY_PORT}
            - NATS_SERVERS=nats://nats-server:4222

    auth-ms:
        build:
            context: ./auth-ms
            dockerfile: dockerfile.prod
        image: auth-ms
        environment:
            - PORT=3004
            - NATS_SERVERS=nats://nats-server:4222
            - DATABASE_URL=${AUTH_DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}

    products-ms:
        build:
            context: ./products-ms
            dockerfile: dockerfile.prod
        image: products-ms
        environment:
            - PORT=3001
            - NATS_SERVERS=nats://nats-server:4222
            - DATABASE_URL=file:./dev.db

    orders-ms:
        build:
            context: ./orders-ms
            dockerfile: dockerfile.prod
            args:
                - ORDERS_DATABASE_URL_PRO=${ORDERS_DATABASE_URL_PRO}
        image: orders-ms
        environment:
            - PORT=3002
            - NATS_SERVERS=nats://nats-server:4222
            - DATABASE_URL=${ORDERS_DATABASE_URL_PRO}

    payments-ms:
        build:
            context: ./payments-ms
            dockerfile: dockerfile.prod
        image: payments-ms
        ports:
            - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
        environment:
            - PORT=${PAYMENTS_MS_PORT}
            - NATS_SERVERS=nats://nats-server:4222
            - STRIPE_SECRET=${PAYMENTS_STRIPE_SECRET}
            - STRIPE_SUCCESS_URL=${PAYMENTS_STRIPE_SUCCESS_URL}
            - STRIPE_CANCELLED_URL=${PAYMENTS_STRIPE_CANCELLED_URL}
            - STRIPE_ENDPOINT_SECRET=${PAYMENTS_STRIPE_ENDPOINT_SECRET}
