apiVersion: apps/v1
kind: Deployment
metadata:
    creationTimestamp: null
    labels:
        app: payments-ms
    name: payments-ms
spec:
    replicas: 1
    selector:
        matchLabels:
            app: payments-ms
    strategy: {}
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: payments-ms
        spec:
            containers:
                - image: europe-southwest1-docker.pkg.dev/tienda-microservices-430107/tienda-microservices/payments-ms
                  name: payments-ms
                  env:
                      - name: PORT
                        value: "3003"
                      - name: NATS_SERVERS
                        value: "nats://nats"
                      - name: STRIPE_SUCCESS_URL
                        value: "http://localhost:32470/payments/success"
                      - name: STRIPE_CANCELLED_URL
                        value: "http://localhost:32470/payments/success"
                      - name: STRIPE_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: payments-secrets
                                key: stripe_secret
                      - name: STRIPE_ENDPOINT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: payments-secrets
                                key: stripe_endpoint_secret
                  resources: {}
status: {}
